---
title: "IFCD0021 Official Docs"
categories: [ifcd0021, training] 
---

## Identificació del Certificat de Professionalitat
- Denominació: **Fullstack júnior web developer amb Java**
- Codi: **IFCD0021**
- Hores: 270h
- Família professional: Informàtica i comunicacions
- Àrea professional: Desenvolupament
- Nivell de qualificació professional: 2
- Qualificació professional de referència: IFCD0021 - ullstack júnior web developer amb Java

## Documentació


- [PROGRAMA Formatiu: Fullstack júnior web developer amb Java](/images/ifcd0021-24/IFCD0021.pdf){#ifcd0021-fitxa}
- [Fitxa: Fullstack júnior web developer amb Java](/images/ifcd0021-24/IFCD0021%20Fitxa%20web%20FULLSTACK%20J%C3%9ANIOR%20WEB%20DEVELOPER%20AMB%20JAVA.pdf){#ifcd0021-fitxa}



## Programa formatiu

1. Introducció a la programació i al disseny de programari amb Java (5h)
2. Programació orientada a objectes amb Java (75h)
3. Bases de dades SQL (MySQL) (30h)
4. Desenvolupament d'APIs amb Spring Framework (75h)
5. Desenvolupament d'interfícies d'usuari web amb Angular (75h)


## Competència general

> Desenvolupar programari per a aplicacions web full stack que incloguin tant l’entorn client (front end) com el
servidor (back end) amb el llenguatge de programació Java, Spring i Angular.

> El programador web s'encarrega de desenvolupar aplicacions web pels navegadors en entorn client i servidor(full stack) amb Java, el framework Spring, Angular i MySQL.
Ocupacions: desenvolupador d’aplicacions web, programador/a, analista, tècnic web ...
Tecnologies: HTML, CSS, javascript, Angular, SQL, Spring, Java...

